/**
 * Preview Status Constants
 *
 * LOCKED LIFECYCLE:
 * INIT → PREPARING_TEMPLATE → INSTALLING_DEPENDENCIES →
 * STARTING_PREVIEW_SERVER → PREVIEW_READY → COMPLETED
 */

export const PREVIEW_STATUS = {
  INIT: "INIT",
  PREPARING_TEMPLATE: "PREPARING_TEMPLATE",
  INSTALLING_DEPENDENCIES: "INSTALLING_DEPENDENCIES",
  STARTING_PREVIEW_SERVER: "STARTING_PREVIEW_SERVER",
  PREVIEW_READY: "PREVIEW_READY",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const PREVIEW_STATUS_ORDER = [
  "INIT",
  "PREPARING_TEMPLATE",
  "INSTALLING_DEPENDENCIES",
  "STARTING_PREVIEW_SERVER",
  "PREVIEW_READY",
  "COMPLETED",
];

export function isTerminalStatus(status) {
  return (
    status === PREVIEW_STATUS.COMPLETED || status === PREVIEW_STATUS.FAILED
  );
}
