/**
 * Executor Agent
 * 
 * Responsible for generating code based on task specifications.
 */

import { BaseAgent } from './base.agent.js';
import type { AgentContext } from '../types/agent.types.js';
import type { AgentMessage, ExecuteTaskPayload, TaskCompletePayload } from '../types/message.types.js';
import type { Task, Artifact, TaskError } from '../types/task.types.js';
import { Sandbox } from '../core/sandbox.js';
import { PatternStore } from '../memory/patterns.js';
import path from 'path';

// Code templates by task type
const CODE_TEMPLATES: Record<string, string> = {
  'setup-nextjs': `// package.json for Next.js project
{
  "name": "{{projectName}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "typescript": "^5.0.0"
  }
}`,

  'prisma-schema': `// prisma/schema.prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}`,

  'api-route': `// src/app/api/{{entity}}/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(request: NextRequest) {
  try {
    const items = await prisma.{{entity}}.findMany();
    return NextResponse.json({ data: items });
  } catch (error) {
    console.error('GET Error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch items' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const item = await prisma.{{entity}}.create({ data: body });
    return NextResponse.json({ data: item }, { status: 201 });
  } catch (error) {
    console.error('POST Error:', error);
    return NextResponse.json(
      { error: 'Failed to create item' },
      { status: 500 }
    );
  }
}`,

  'component': `// src/components/{{name}}.tsx
'use client';

import React from 'react';

interface {{name}}Props {
  className?: string;
}

export function {{name}}({ className }: {{name}}Props) {
  return (
    <div className={className}>
      <h2>{{name}}</h2>
    </div>
  );
}`,

  'page': `// src/app/{{path}}/page.tsx
import React from 'react';

export default function {{name}}Page() {
  return (
    <main className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold">{{name}}</h1>
    </main>
  );
}`,

  'layout': `// src/app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '{{projectName}}',
  description: 'Generated by AI Agent Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,

  'prisma-client': `// src/lib/prisma.ts
import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}`,

  'tailwind-config': `// tailwind.config.ts
import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;`,

  'globals-css': `/* src/app/globals.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
}`,
};

export class ExecutorAgent extends BaseAgent {
  private sandbox: Sandbox;
  private patternStore: PatternStore;

  constructor(context: AgentContext) {
    super(
      {
        name: 'executor',
        maxConcurrency: 1,
        retryAttempts: 3,
        timeoutMs: 120000,
      },
      context
    );

    this.sandbox = new Sandbox(context.workingDirectory);
    this.patternStore = new PatternStore(
      path.join(context.workingDirectory, '.agent', 'patterns')
    );
  }

  protected async onInitialize(): Promise<void> {
    await this.patternStore.initialize();
  }

  protected registerHandlers(): void {
    this.handlers.set('execute_task', {
      action: 'execute_task',
      handler: this.handleExecuteTask.bind(this),
    });

    this.handlers.set('generate_file', {
      action: 'generate_file',
      handler: this.handleGenerateFile.bind(this),
    });
  }

  /**
   * Execute a task
   */
  private async handleExecuteTask(
    message: AgentMessage<ExecuteTaskPayload>
  ): Promise<void> {
    const { taskId, taskType, inputs } = message.payload;
    this.log(`Executing task: ${taskId} (type: ${taskType})`);

    const artifacts: Artifact[] = [];
    const errors: TaskError[] = [];

    try {
      // Generate artifacts based on task type
      const generated = await this.generateArtifacts(taskType, inputs);
      artifacts.push(...generated);

      // Validate generated code
      for (const artifact of artifacts) {
        const validation = this.sandbox.validateContent(artifact.content);
        if (validation.warnings.length > 0) {
          this.log(`Warnings for ${artifact.path}: ${validation.warnings.join(', ')}`, 'warn');
        }
      }

      const response: TaskCompletePayload = {
        taskId,
        success: true,
        artifacts: artifacts.map((a) => ({ path: a.path, action: a.action })),
      };

      await this.respond(message, response);
      this.log(`Task completed: ${taskId}, generated ${artifacts.length} artifacts`);
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      errors.push({
        code: 'EXECUTION_ERROR',
        message: errorMsg,
        severity: 'error',
      });

      await this.respond(message, {
        taskId,
        success: false,
        artifacts: [],
        errors,
      });
    }
  }

  /**
   * Generate a specific file
   */
  private async handleGenerateFile(
    message: AgentMessage<{ templateKey: string; variables: Record<string, string>; outputPath: string }>
  ): Promise<void> {
    const { templateKey, variables, outputPath } = message.payload;

    // Validate output path
    const pathValidation = this.sandbox.validateFilePath(outputPath);
    if (!pathValidation.valid) {
      await this.respond(message, { success: false, error: pathValidation.reason });
      return;
    }

    // Get template and apply variables
    const template = CODE_TEMPLATES[templateKey];
    if (!template) {
      await this.respond(message, { success: false, error: `Unknown template: ${templateKey}` });
      return;
    }

    const content = this.applyVariables(template, variables);

    const artifact: Artifact = {
      type: 'file',
      path: outputPath,
      content,
      action: 'create',
    };

    await this.respond(message, {
      success: true,
      artifact,
    });
  }

  /**
   * Generate artifacts for a task type
   */
  private async generateArtifacts(
    taskType: string,
    inputs: Record<string, unknown>
  ): Promise<Artifact[]> {
    const artifacts: Artifact[] = [];
    const projectName = (inputs.projectName as string) || 'my-app';

    switch (taskType) {
      case 'setup':
        artifacts.push({
          type: 'file',
          path: 'package.json',
          content: this.applyVariables(CODE_TEMPLATES['setup-nextjs'], { projectName }),
          action: 'create',
        });
        break;

      case 'schema':
        artifacts.push({
          type: 'file',
          path: 'prisma/schema.prisma',
          content: CODE_TEMPLATES['prisma-schema'],
          action: 'create',
        });
        artifacts.push({
          type: 'file',
          path: 'src/lib/prisma.ts',
          content: CODE_TEMPLATES['prisma-client'],
          action: 'create',
        });
        break;

      case 'config':
        if (inputs.configType === 'tailwind') {
          artifacts.push({
            type: 'config',
            path: 'tailwind.config.ts',
            content: CODE_TEMPLATES['tailwind-config'],
            action: 'create',
          });
          artifacts.push({
            type: 'file',
            path: 'src/app/globals.css',
            content: CODE_TEMPLATES['globals-css'],
            action: 'create',
          });
        }
        break;

      case 'api':
        const entity = (inputs.entity as string) || 'item';
        artifacts.push({
          type: 'file',
          path: `src/app/api/${entity}/route.ts`,
          content: this.applyVariables(CODE_TEMPLATES['api-route'], { entity }),
          action: 'create',
        });
        break;

      case 'component':
        const componentName = (inputs.name as string) || 'Component';
        artifacts.push({
          type: 'file',
          path: `src/components/${componentName}.tsx`,
          content: this.applyVariables(CODE_TEMPLATES['component'], { name: componentName }),
          action: 'create',
        });
        break;

      case 'page':
        const pageName = (inputs.name as string) || 'Home';
        const pagePath = (inputs.path as string) || '';
        artifacts.push({
          type: 'file',
          path: `src/app/${pagePath}/page.tsx`,
          content: this.applyVariables(CODE_TEMPLATES['page'], { name: pageName, path: pagePath }),
          action: 'create',
        });
        break;

      default:
        this.log(`Unknown task type: ${taskType}`, 'warn');
    }

    return artifacts;
  }

  /**
   * Apply variables to a template
   */
  private applyVariables(template: string, variables: Record<string, string>): string {
    let result = template;
    for (const [key, value] of Object.entries(variables)) {
      result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
    }
    return result;
  }
}
